# Generated by Django 4.1.12 on 2023-12-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_person_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('can_view_other_persons', 'Can view other persons')]},
        ),
    ]
